version: "3.8"

services:
    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: yourpassword
            MYSQL_DATABASE: yourdatabase
            MYSQL_USER: youruser
            MYSQL_PASSWORD: yourpassword
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
